namespace Softwyx.CareerLog.Persistence.Models;

/// <summary>
/// JSON dictionary keys on <see cref="RaidRecord.VanillaSessionCountersLong"/> and
/// <see cref="RaidRecord.VanillaSessionCountersFloat"/>. Each matches a
/// <see cref="SessionCounterTypesAbstractClass"/> static field name; captured at raid end by
/// <see cref="VanillaSessionCounterSnapshot"/>.
/// </summary>
internal static class VanillaSessionCounterKeys{
    public const string ExpKillBase               = nameof(SessionCounterTypesAbstractClass.ExpKillBase);
    public const string ExpKillBodyPartBonus      = nameof(SessionCounterTypesAbstractClass.ExpKillBodyPartBonus);
    public const string ExpKillStreakBonus        = nameof(SessionCounterTypesAbstractClass.ExpKillStreakBonus);
    public const string ExpItemLooting            = nameof(SessionCounterTypesAbstractClass.ExpItemLooting);
    public const string ExpDoorUnlocked           = nameof(SessionCounterTypesAbstractClass.ExpDoorUnlocked);
    public const string ExpDoorBreached           = nameof(SessionCounterTypesAbstractClass.ExpDoorBreached);
    public const string ExpDamage                 = nameof(SessionCounterTypesAbstractClass.ExpDamage);
    public const string ExpHeal                   = nameof(SessionCounterTypesAbstractClass.ExpHeal);
    public const string ExpEnergy                 = nameof(SessionCounterTypesAbstractClass.ExpEnergy);
    public const string ExpHydration              = nameof(SessionCounterTypesAbstractClass.ExpHydration);
    public const string ExpExitStatus             = nameof(SessionCounterTypesAbstractClass.ExpExitStatus);
    public const string ExpTrigger                = nameof(SessionCounterTypesAbstractClass.ExpTrigger);
    public const string ExpStationaryContainer    = nameof(SessionCounterTypesAbstractClass.ExpStationaryContainer);
    public const string ExpExamine                = nameof(SessionCounterTypesAbstractClass.ExpExamine);
    public const string Deaths                    = nameof(SessionCounterTypesAbstractClass.Deaths);
    public const string Kills                     = nameof(SessionCounterTypesAbstractClass.Kills);
    public const string KilledLevel0010           = nameof(SessionCounterTypesAbstractClass.KilledLevel0010);
    public const string KilledLevel1030           = nameof(SessionCounterTypesAbstractClass.KilledLevel1030);
    public const string KilledLevel3050           = nameof(SessionCounterTypesAbstractClass.KilledLevel3050);
    public const string KilledLevel5070           = nameof(SessionCounterTypesAbstractClass.KilledLevel5070);
    public const string KilledLevel7099           = nameof(SessionCounterTypesAbstractClass.KilledLevel7099);
    public const string KilledLevel100            = nameof(SessionCounterTypesAbstractClass.KilledLevel100);
    public const string KilledBear                = nameof(SessionCounterTypesAbstractClass.KilledBear);
    public const string KilledUsec                = nameof(SessionCounterTypesAbstractClass.KilledUsec);
    public const string KilledSavage              = nameof(SessionCounterTypesAbstractClass.KilledSavage);
    public const string KilledPmc                 = nameof(SessionCounterTypesAbstractClass.KilledPmc);
    public const string KilledBoss                = nameof(SessionCounterTypesAbstractClass.KilledBoss);
    public const string KilledWithKnife           = nameof(SessionCounterTypesAbstractClass.KilledWithKnife);
    public const string KilledWithPistol          = nameof(SessionCounterTypesAbstractClass.KilledWithPistol);
    public const string KilledWithSmg             = nameof(SessionCounterTypesAbstractClass.KilledWithSmg);
    public const string KilledWithShotgun         = nameof(SessionCounterTypesAbstractClass.KilledWithShotgun);
    public const string KilledWithAssaultRifle    = nameof(SessionCounterTypesAbstractClass.KilledWithAssaultRifle);
    public const string KilledWithAssaultCarbine  = nameof(SessionCounterTypesAbstractClass.KilledWithAssaultCarbine);
    public const string KilledWithGrenadeLauncher = nameof(SessionCounterTypesAbstractClass.KilledWithGrenadeLauncher);
    public const string KilledWithMachineGun      = nameof(SessionCounterTypesAbstractClass.KilledWithMachineGun);
    public const string KilledWithMarksmanRifle   = nameof(SessionCounterTypesAbstractClass.KilledWithMarksmanRifle);
    public const string KilledWithSniperRifle     = nameof(SessionCounterTypesAbstractClass.KilledWithSniperRifle);
    public const string KilledWithSpecialWeapon   = nameof(SessionCounterTypesAbstractClass.KilledWithSpecialWeapon);
    public const string KilledWithThrowWeapon     = nameof(SessionCounterTypesAbstractClass.KilledWithThrowWeapon);
    public const string KilledWithTripwires       = nameof(SessionCounterTypesAbstractClass.KilledWithTripwires);
    public const string HeadShots                 = nameof(SessionCounterTypesAbstractClass.HeadShots);
    public const string BloodLoss                 = nameof(SessionCounterTypesAbstractClass.BloodLoss);
    public const string BodyPartsDestroyed        = nameof(SessionCounterTypesAbstractClass.BodyPartsDestroyed);
    public const string Heal                      = nameof(SessionCounterTypesAbstractClass.Heal);
    public const string Fractures                 = nameof(SessionCounterTypesAbstractClass.Fractures);
    public const string Contusions                = nameof(SessionCounterTypesAbstractClass.Contusions);
    public const string Dehydrations              = nameof(SessionCounterTypesAbstractClass.Dehydrations);
    public const string Exhaustions               = nameof(SessionCounterTypesAbstractClass.Exhaustions);
    public const string Medicines                 = nameof(SessionCounterTypesAbstractClass.Medicines);
    public const string UsedFoods                 = nameof(SessionCounterTypesAbstractClass.UsedFoods);
    public const string UsedDrinks                = nameof(SessionCounterTypesAbstractClass.UsedDrinks);
    public const string Pedometer                 = nameof(SessionCounterTypesAbstractClass.Pedometer);
    public const string BodiesLooted              = nameof(SessionCounterTypesAbstractClass.BodiesLooted);
    public const string SafeLooted                = nameof(SessionCounterTypesAbstractClass.SafeLooted);
    public const string Triggers                  = nameof(SessionCounterTypesAbstractClass.Triggers);
    public const string LockableContainers        = nameof(SessionCounterTypesAbstractClass.LockableContainers);
    public const string Weapons                   = nameof(SessionCounterTypesAbstractClass.Weapons);
    public const string Ammunitions               = nameof(SessionCounterTypesAbstractClass.Ammunitions);
    public const string Mods                      = nameof(SessionCounterTypesAbstractClass.Mods);
    public const string ThrowWeapons              = nameof(SessionCounterTypesAbstractClass.ThrowWeapons);
    public const string SpecialItems              = nameof(SessionCounterTypesAbstractClass.SpecialItems);
    public const string FoodDrinks                = nameof(SessionCounterTypesAbstractClass.FoodDrinks);
    public const string Keys                      = nameof(SessionCounterTypesAbstractClass.Keys);
    public const string BartItems                 = nameof(SessionCounterTypesAbstractClass.BartItems);
    public const string MobContainers             = nameof(SessionCounterTypesAbstractClass.MobContainers);
    public const string Equipments                = nameof(SessionCounterTypesAbstractClass.Equipments);
    public const string CauseBodyDamage           = nameof(SessionCounterTypesAbstractClass.CauseBodyDamage);
    public const string CauseArmorDamage          = nameof(SessionCounterTypesAbstractClass.CauseArmorDamage);
    public const string HitCount                  = nameof(SessionCounterTypesAbstractClass.HitCount);
    public const string LongShots                 = nameof(SessionCounterTypesAbstractClass.LongShots);
    public const string LongestShot               = nameof(SessionCounterTypesAbstractClass.LongestShot);
    public const string LongestKillShot           = nameof(SessionCounterTypesAbstractClass.LongestKillShot);
    public const string LongestKillShotOnBot      = nameof(SessionCounterTypesAbstractClass.LongestKillShotOnBot);
    public const string LongestKillStreak         = nameof(SessionCounterTypesAbstractClass.LongestKillStreak);
    public const string ExpKill                   = nameof(SessionCounterTypesAbstractClass.ExpKill);
    public const string ExpLooting                = nameof(SessionCounterTypesAbstractClass.ExpLooting);
    public const string MoneyRub                  = nameof(SessionCounterTypesAbstractClass.MoneyRub);
    public const string MoneyEur                  = nameof(SessionCounterTypesAbstractClass.MoneyEur);
    public const string MoneyUsd                  = nameof(SessionCounterTypesAbstractClass.MoneyUsd);
    public const string AmmoUsed                  = nameof(SessionCounterTypesAbstractClass.AmmoUsed);
    public const string AmmoReached               = nameof(SessionCounterTypesAbstractClass.AmmoReached);
    public const string TriggersVisited           = nameof(SessionCounterTypesAbstractClass.TriggersVisited);
    public const string BodyPartHeadDamage        = nameof(SessionCounterTypesAbstractClass.BodyPartHeadDamage);
    public const string BodyPartChestDamage       = nameof(SessionCounterTypesAbstractClass.BodyPartChestDamage);
    public const string BodyPartStomachDamage     = nameof(SessionCounterTypesAbstractClass.BodyPartStomachDamage);
    public const string BodyPartLeftArmDamage     = nameof(SessionCounterTypesAbstractClass.BodyPartLeftArmDamage);
    public const string BodyPartRightArmDamage    = nameof(SessionCounterTypesAbstractClass.BodyPartRightArmDamage);
    public const string BodyPartLeftLegDamage     = nameof(SessionCounterTypesAbstractClass.BodyPartLeftLegDamage);
    public const string BodyPartRightLegDamage    = nameof(SessionCounterTypesAbstractClass.BodyPartRightLegDamage);
    public const string CombatDamage              = nameof(SessionCounterTypesAbstractClass.CombatDamage);
    public const string DailyTotalCompleteCount   = nameof(SessionCounterTypesAbstractClass.DailyTotalCompleteCount);
    public const string DailyVeryEasyCount        = nameof(SessionCounterTypesAbstractClass.DailyVeryEasyCount);
    public const string DailyEasyCount            = nameof(SessionCounterTypesAbstractClass.DailyEasyCount);
    public const string DailyMediumCount          = nameof(SessionCounterTypesAbstractClass.DailyMediumCount);
    public const string DailyHardCount            = nameof(SessionCounterTypesAbstractClass.DailyHardCount);
    public const string DailyVeryHardCount        = nameof(SessionCounterTypesAbstractClass.DailyVeryHardCount);
    public const string DailyAvgCompletionTimeDay = nameof(SessionCounterTypesAbstractClass.DailyAvgCompletionTimeDay);
    public const string DailyAvgCompletionTimeWeek =
        nameof(SessionCounterTypesAbstractClass.DailyAvgCompletionTimeWeek);
    public const string DailyMaxCompleteStreak = nameof(SessionCounterTypesAbstractClass.DailyMaxCompleteStreak);
    public const string DailyCurrentCompleteStreak =
        nameof(SessionCounterTypesAbstractClass.DailyCurrentCompleteStreak);
    public const string DailyFavoriteQuestType = nameof(SessionCounterTypesAbstractClass.DailyFavoriteQuestType);
    public const string DailyTotalFailCount    = nameof(SessionCounterTypesAbstractClass.DailyTotalFailCount);
    public const string DailyMaxFailStreak     = nameof(SessionCounterTypesAbstractClass.DailyMaxFailStreak);
    public const string DailyMoneyEarned       = nameof(SessionCounterTypesAbstractClass.DailyMoneyEarned);
    public const string DailyExpEarned         = nameof(SessionCounterTypesAbstractClass.DailyExpEarned);
}
